start-at-login = true
accordion-padding = 30

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"


[mode.main.binding]
alt-f = 'fullscreen'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-o = 'workspace O'
alt-m = 'workspace M'
alt-r = 'workspace R'
alt-s = 'workspace S'
alt-w = 'workspace W'
alt-b = 'workspace B'
alt-q = 'workspace Q'

alt-h = 'focus left'
alt-l = 'focus right'
alt-k = 'focus up'
alt-j = 'focus down'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-o = 'move-node-to-workspace O'
alt-shift-m = 'move-node-to-workspace M'
alt-shift-r = 'move-node-to-workspace R'
alt-shift-w = 'move-node-to-workspace W'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-q = 'move-node-to-workspace Q'
alt-shift-s = 'move-node-to-workspace S'

alt-period = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'
alt-shift-0 = 'mode resize'


[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
b = 'balance-sizes'

minus = 'resize smart -50'
equal = 'resize smart +50'

enter = 'mode main'
esc = 'mode main'

[gaps]
inner.horizontal = 15
inner.vertical = 15
outer.left = 20
outer.bottom = 20
outer.top = 20
outer.right = 20

[workspace-to-monitor-force-assignment]
1 = "main"
2 = "secondary"
W = "secondary"
F = "main"
3 = "main"
4 = "main"
5 = "main"
B = "main"


[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = "move-node-to-workspace O"

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = "move-node-to-workspace M"

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace S"

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'Cisco-Systems.Spark'
run = "move-node-to-workspace W"

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace Q"


[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = "move-node-to-workspace R"
